name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
#  build:
#
#    runs-on: macos-latest
#
#    strategy:
#      matrix:
#        java-version: ['17']
#
#    steps:
#    - uses: actions/checkout@v4
#    - name: set up JDK 17
#      uses: actions/setup-java@v4
#      with:
#        java-version: ${{matrix.java-version}}
#        distribution: 'temurin'
#        cache: gradle
#
#    - name: Grant execute permission for gradlew
#      run: chmod +x gradlew
#    - name: Build with Gradle
#      run: ./gradlew build

#  lint:
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        java-version: [ '17' ]
#
#
#    steps:
#      - name: Checkout the code
#        uses: actions/checkout@v4
#
#      - uses: actions/setup-java@v4
#        with:
#          java-version: ${{matrix.java-version}}
#          distribution: 'temurin'
#          cache: gradle
#
#      - run: ./gradlew app:lintReportDebug
#
#      - uses: actions/upload-artifact@v4
#        with:
#          name: lint-result.html
#          path: app/build/reports/lint-results-debug.html

#  unit-test:
#    needs: [lint]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: 'gradle'
#      - run: ./gradlew test
#
#      - uses: actions/upload-artifact@v4
#        with:
#          name: unit_test_report
#          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
#    needs: [unit-test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
      - uses: actions/upload-artifact@v2
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/


      - name: Clone TranhGio/CI-Experiment-Automation PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'main'
          owner: 'TranhGio'
          repository: 'CI-Experiment-Automation'
      - run: ls -a