name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: ['17']

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: ${{matrix.java-version}}
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Connected check on android emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 31
        script: ./gradlew connectedCheck

  run-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ '17' ]


    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'temurin'
          cache: gradle

      - name: Run lint debug report
        run: ./gradlew app:lintReportDebug

      - name: Upload the artifact of lint report
        uses: actions/upload-artifact@v4
        with:
          name: lint-result.html
          path: app/build/reports/lint-results-debug.html
